# ip:port
serverIp: 47.106.247.251

spring:
  application:
    name: movie-sys
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  datasource:
    name: movie_sys
    url: jdbc:mysql://mysql:3306/moviesys?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MyNewPass4!
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
  messages:
    encoding: UTF-8
    basename: i18n/abt_messages
    use-code-as-default-message: true
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
#    encoding: UTF-8
#    cache: false
#    servlet:
#      content-type: text/html

sever:
  servlet:
    session:
      timeout: 259200

mybatis:
  basepackage: team.csjr.moviesys.mapper
  mapper-locations: ["classpath*:mapper/**/*.xml"]

logging:
  level:
    team.csjr.moviesys.mapper: DEBUG

